import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import "@/logaxp/utils/gsap";
import { Geist } from "next/font/google";
import CustomLenis, { BackToTop } from "../components";
import { Navbar } from "../sections";
import Cursor from "../components/Cursor";

const mangoGrotesque = localFont({
  src: [
    {
      path: "../../public/fonts/mango/extrabold.woff2",
      weight: "900",
    },
    {
      path: "../../public/fonts/mango/regular.woff2",
      weight: "400",
    },
    {
      path: "../../public/fonts/mango/medium.woff2",
      weight: "500",
    },
    {
      path: "../../public/fonts/mango/semibold.woff2",
      weight: "600",
    },
    {
      path: "../../public/fonts/mango/light.woff2",
      weight: "300",
    },
  ],
  variable: "--font-mango",
});

const geist = Geist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "LogaXP - Software Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${mangoGrotesque.variable} ${geist.variable}  antialiased`}
      >
        <CustomLenis>
          <Navbar />
          {children}
          <BackToTop />
          <Cursor />
        </CustomLenis>
      </body>
    </html>
  );
}
